/* 
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * OpenAPI spec version: 1.4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// authorisation object
    /// </summary>
    [DataContract]
        public partial class Login :  IEquatable<Login>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Login" /> class.
        /// </summary>
        /// <param name="customerid">Your customer ID, available from your account area at https://thesmsworks.co.uk/user/login.</param>
        /// <param name="key">API Key, available from your account area at https://thesmsworks.co.uk/user/login.</param>
        /// <param name="secret">API Secret, available from your account area at https://thesmsworks.co.uk/user/login.</param>
        public Login(string customerid = default(string), string key = default(string), string secret = default(string))
        {
            this.Customerid = customerid;
            this.Key = key;
            this.Secret = secret;
        }
        
        /// <summary>
        /// Your customer ID, available from your account area at https://thesmsworks.co.uk/user/login
        /// </summary>
        /// <value>Your customer ID, available from your account area at https://thesmsworks.co.uk/user/login</value>
        [DataMember(Name="customerid", EmitDefaultValue=false)]
        public string Customerid { get; set; }

        /// <summary>
        /// API Key, available from your account area at https://thesmsworks.co.uk/user/login
        /// </summary>
        /// <value>API Key, available from your account area at https://thesmsworks.co.uk/user/login</value>
        [DataMember(Name="key", EmitDefaultValue=false)]
        public string Key { get; set; }

        /// <summary>
        /// API Secret, available from your account area at https://thesmsworks.co.uk/user/login
        /// </summary>
        /// <value>API Secret, available from your account area at https://thesmsworks.co.uk/user/login</value>
        [DataMember(Name="secret", EmitDefaultValue=false)]
        public string Secret { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Login {\n");
            sb.Append("  Customerid: ").Append(Customerid).Append("\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  Secret: ").Append(Secret).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Login);
        }

        /// <summary>
        /// Returns true if Login instances are equal
        /// </summary>
        /// <param name="input">Instance of Login to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Login input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Customerid == input.Customerid ||
                    (this.Customerid != null &&
                    this.Customerid.Equals(input.Customerid))
                ) && 
                (
                    this.Key == input.Key ||
                    (this.Key != null &&
                    this.Key.Equals(input.Key))
                ) && 
                (
                    this.Secret == input.Secret ||
                    (this.Secret != null &&
                    this.Secret.Equals(input.Secret))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Customerid != null)
                    hashCode = hashCode * 59 + this.Customerid.GetHashCode();
                if (this.Key != null)
                    hashCode = hashCode * 59 + this.Key.GetHashCode();
                if (this.Secret != null)
                    hashCode = hashCode * 59 + this.Secret.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
