/*
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.
 *
 * The version of the OpenAPI document: 1.9.0
 * Contact: support@thesmsworks.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing OneTimePasswordApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class OneTimePasswordApiTests : IDisposable
    {
        private OneTimePasswordApi instance;

        public OneTimePasswordApiTests()
        {
            instance = new OneTimePasswordApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OneTimePasswordApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' OneTimePasswordApi
            //Assert.IsType<OneTimePasswordApi>(instance);
        }

        /// <summary>
        /// Test OtpMessageidGet
        /// </summary>
        [Fact]
        public void OtpMessageidGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string messageid = null;
            //var response = instance.OtpMessageidGet(messageid);
            //Assert.IsType<OTPVerifyResponse>(response);
        }

        /// <summary>
        /// Test OtpSendPost
        /// </summary>
        [Fact]
        public void OtpSendPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OTP otp = null;
            //var response = instance.OtpSendPost(otp);
            //Assert.IsType<OTPResponse>(response);
        }

        /// <summary>
        /// Test OtpVerifyPost
        /// </summary>
        [Fact]
        public void OtpVerifyPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OTPVerify passcode = null;
            //var response = instance.OtpVerifyPost(passcode);
            //Assert.IsType<OTPVerifyResponse>(response);
        }
    }
}
