/* 
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * OpenAPI spec version: 1.4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IUtilsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns a sample error object for the given error code. Useful for designing code to react to errors when they occur for real.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="errorcode">The code of the error you would like returned</param>
        /// <returns>ExtendedErrorModel</returns>
        ExtendedErrorModel GetError (string errorcode);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns a sample error object for the given error code. Useful for designing code to react to errors when they occur for real.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="errorcode">The code of the error you would like returned</param>
        /// <returns>ApiResponse of ExtendedErrorModel</returns>
        ApiResponse<ExtendedErrorModel> GetErrorWithHttpInfo (string errorcode);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns the customer ID to the caller
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>TestResponse</returns>
        TestResponse Test ();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns the customer ID to the caller
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of TestResponse</returns>
        ApiResponse<TestResponse> TestWithHttpInfo ();
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns a sample error object for the given error code. Useful for designing code to react to errors when they occur for real.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="errorcode">The code of the error you would like returned</param>
        /// <returns>Task of ExtendedErrorModel</returns>
        System.Threading.Tasks.Task<ExtendedErrorModel> GetErrorAsync (string errorcode);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns a sample error object for the given error code. Useful for designing code to react to errors when they occur for real.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="errorcode">The code of the error you would like returned</param>
        /// <returns>Task of ApiResponse (ExtendedErrorModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<ExtendedErrorModel>> GetErrorAsyncWithHttpInfo (string errorcode);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns the customer ID to the caller
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of TestResponse</returns>
        System.Threading.Tasks.Task<TestResponse> TestAsync ();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns the customer ID to the caller
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (TestResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<TestResponse>> TestAsyncWithHttpInfo ();
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class UtilsApi : IUtilsApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="UtilsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UtilsApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UtilsApi"/> class
        /// </summary>
        /// <returns></returns>
        public UtilsApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UtilsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public UtilsApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  Returns a sample error object for the given error code. Useful for designing code to react to errors when they occur for real.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="errorcode">The code of the error you would like returned</param>
        /// <returns>ExtendedErrorModel</returns>
        public ExtendedErrorModel GetError (string errorcode)
        {
             ApiResponse<ExtendedErrorModel> localVarResponse = GetErrorWithHttpInfo(errorcode);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Returns a sample error object for the given error code. Useful for designing code to react to errors when they occur for real.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="errorcode">The code of the error you would like returned</param>
        /// <returns>ApiResponse of ExtendedErrorModel</returns>
        public ApiResponse< ExtendedErrorModel > GetErrorWithHttpInfo (string errorcode)
        {
            // verify the required parameter 'errorcode' is set
            if (errorcode == null)
                throw new ApiException(400, "Missing required parameter 'errorcode' when calling UtilsApi->GetError");

            var localVarPath = "/utils/errors/{errorcode}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (errorcode != null) localVarPathParams.Add("errorcode", this.Configuration.ApiClient.ParameterToString(errorcode)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetError", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ExtendedErrorModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ExtendedErrorModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ExtendedErrorModel)));
        }

        /// <summary>
        ///  Returns a sample error object for the given error code. Useful for designing code to react to errors when they occur for real.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="errorcode">The code of the error you would like returned</param>
        /// <returns>Task of ExtendedErrorModel</returns>
        public async System.Threading.Tasks.Task<ExtendedErrorModel> GetErrorAsync (string errorcode)
        {
             ApiResponse<ExtendedErrorModel> localVarResponse = await GetErrorAsyncWithHttpInfo(errorcode);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Returns a sample error object for the given error code. Useful for designing code to react to errors when they occur for real.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="errorcode">The code of the error you would like returned</param>
        /// <returns>Task of ApiResponse (ExtendedErrorModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ExtendedErrorModel>> GetErrorAsyncWithHttpInfo (string errorcode)
        {
            // verify the required parameter 'errorcode' is set
            if (errorcode == null)
                throw new ApiException(400, "Missing required parameter 'errorcode' when calling UtilsApi->GetError");

            var localVarPath = "/utils/errors/{errorcode}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (errorcode != null) localVarPathParams.Add("errorcode", this.Configuration.ApiClient.ParameterToString(errorcode)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetError", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ExtendedErrorModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ExtendedErrorModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ExtendedErrorModel)));
        }

        /// <summary>
        ///  Returns the customer ID to the caller
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>TestResponse</returns>
        public TestResponse Test ()
        {
             ApiResponse<TestResponse> localVarResponse = TestWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Returns the customer ID to the caller
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of TestResponse</returns>
        public ApiResponse< TestResponse > TestWithHttpInfo ()
        {

            var localVarPath = "/utils/test";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Test", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TestResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (TestResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TestResponse)));
        }

        /// <summary>
        ///  Returns the customer ID to the caller
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of TestResponse</returns>
        public async System.Threading.Tasks.Task<TestResponse> TestAsync ()
        {
             ApiResponse<TestResponse> localVarResponse = await TestAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Returns the customer ID to the caller
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (TestResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<TestResponse>> TestAsyncWithHttpInfo ()
        {

            var localVarPath = "/utils/test";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Test", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TestResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (TestResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TestResponse)));
        }

    }
}
