/*
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.
 *
 * The version of the OpenAPI document: 1.9.0
 * Contact: support@thesmsworks.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing BatchMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BatchMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BatchMessage
        //private BatchMessage instance;

        public BatchMessageTests()
        {
            // TODO uncomment below to create an instance of BatchMessage
            //instance = new BatchMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BatchMessage
        /// </summary>
        [Fact]
        public void BatchMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" BatchMessage
            //Assert.IsType<BatchMessage>(instance);
        }

        /// <summary>
        /// Test the property 'Sender'
        /// </summary>
        [Fact]
        public void SenderTest()
        {
            // TODO unit test for the property 'Sender'
        }

        /// <summary>
        /// Test the property 'Destinations'
        /// </summary>
        [Fact]
        public void DestinationsTest()
        {
            // TODO unit test for the property 'Destinations'
        }

        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

        /// <summary>
        /// Test the property 'Deliveryreporturl'
        /// </summary>
        [Fact]
        public void DeliveryreporturlTest()
        {
            // TODO unit test for the property 'Deliveryreporturl'
        }

        /// <summary>
        /// Test the property 'Schedule'
        /// </summary>
        [Fact]
        public void ScheduleTest()
        {
            // TODO unit test for the property 'Schedule'
        }

        /// <summary>
        /// Test the property 'Tag'
        /// </summary>
        [Fact]
        public void TagTest()
        {
            // TODO unit test for the property 'Tag'
        }

        /// <summary>
        /// Test the property 'Ttl'
        /// </summary>
        [Fact]
        public void TtlTest()
        {
            // TODO unit test for the property 'Ttl'
        }

        /// <summary>
        /// Test the property 'Validity'
        /// </summary>
        [Fact]
        public void ValidityTest()
        {
            // TODO unit test for the property 'Validity'
        }

        /// <summary>
        /// Test the property 'Ai'
        /// </summary>
        [Fact]
        public void AiTest()
        {
            // TODO unit test for the property 'Ai'
        }
    }
}
