/*
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.
 *
 * The version of the OpenAPI document: 1.9.0
 * Contact: support@thesmsworks.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CancelledMessageResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CancelledMessageResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CancelledMessageResponse
        //private CancelledMessageResponse instance;

        public CancelledMessageResponseTests()
        {
            // TODO uncomment below to create an instance of CancelledMessageResponse
            //instance = new CancelledMessageResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CancelledMessageResponse
        /// </summary>
        [Fact]
        public void CancelledMessageResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CancelledMessageResponse
            //Assert.IsType<CancelledMessageResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Messageid'
        /// </summary>
        [Fact]
        public void MessageidTest()
        {
            // TODO unit test for the property 'Messageid'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
