/*
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.
 *
 * The version of the OpenAPI document: 1.9.0
 * Contact: support@thesmsworks.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing MessageResponseFailurereason
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MessageResponseFailurereasonTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MessageResponseFailurereason
        //private MessageResponseFailurereason instance;

        public MessageResponseFailurereasonTests()
        {
            // TODO uncomment below to create an instance of MessageResponseFailurereason
            //instance = new MessageResponseFailurereason();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MessageResponseFailurereason
        /// </summary>
        [Fact]
        public void MessageResponseFailurereasonInstanceTest()
        {
            // TODO uncomment below to test "IsType" MessageResponseFailurereason
            //Assert.IsType<MessageResponseFailurereason>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Details'
        /// </summary>
        [Fact]
        public void DetailsTest()
        {
            // TODO unit test for the property 'Details'
        }

        /// <summary>
        /// Test the property 'Permanent'
        /// </summary>
        [Fact]
        public void PermanentTest()
        {
            // TODO unit test for the property 'Permanent'
        }
    }
}
