/*
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.
 *
 * The version of the OpenAPI document: 1.9.0
 * Contact: support@thesmsworks.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing MessageResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MessageResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MessageResponse
        //private MessageResponse instance;

        public MessageResponseTests()
        {
            // TODO uncomment below to create an instance of MessageResponse
            //instance = new MessageResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MessageResponse
        /// </summary>
        [Fact]
        public void MessageResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" MessageResponse
            //Assert.IsType<MessageResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Batchid'
        /// </summary>
        [Fact]
        public void BatchidTest()
        {
            // TODO unit test for the property 'Batchid'
        }

        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'Customerid'
        /// </summary>
        [Fact]
        public void CustomeridTest()
        {
            // TODO unit test for the property 'Customerid'
        }

        /// <summary>
        /// Test the property 'Deliveryreporturl'
        /// </summary>
        [Fact]
        public void DeliveryreporturlTest()
        {
            // TODO unit test for the property 'Deliveryreporturl'
        }

        /// <summary>
        /// Test the property 'Destination'
        /// </summary>
        [Fact]
        public void DestinationTest()
        {
            // TODO unit test for the property 'Destination'
        }

        /// <summary>
        /// Test the property 'Failurereason'
        /// </summary>
        [Fact]
        public void FailurereasonTest()
        {
            // TODO unit test for the property 'Failurereason'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Identifier'
        /// </summary>
        [Fact]
        public void IdentifierTest()
        {
            // TODO unit test for the property 'Identifier'
        }

        /// <summary>
        /// Test the property 'Keyword'
        /// </summary>
        [Fact]
        public void KeywordTest()
        {
            // TODO unit test for the property 'Keyword'
        }

        /// <summary>
        /// Test the property 'Messageid'
        /// </summary>
        [Fact]
        public void MessageidTest()
        {
            // TODO unit test for the property 'Messageid'
        }

        /// <summary>
        /// Test the property 'Modified'
        /// </summary>
        [Fact]
        public void ModifiedTest()
        {
            // TODO unit test for the property 'Modified'
        }

        /// <summary>
        /// Test the property 'Schedule'
        /// </summary>
        [Fact]
        public void ScheduleTest()
        {
            // TODO unit test for the property 'Schedule'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Sender'
        /// </summary>
        [Fact]
        public void SenderTest()
        {
            // TODO unit test for the property 'Sender'
        }

        /// <summary>
        /// Test the property 'Tag'
        /// </summary>
        [Fact]
        public void TagTest()
        {
            // TODO unit test for the property 'Tag'
        }
    }
}
