/*
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.
 *
 * The version of the OpenAPI document: 1.9.0
 * Contact: support@thesmsworks.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ScheduledMessageResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScheduledMessageResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ScheduledMessageResponse
        //private ScheduledMessageResponse instance;

        public ScheduledMessageResponseTests()
        {
            // TODO uncomment below to create an instance of ScheduledMessageResponse
            //instance = new ScheduledMessageResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ScheduledMessageResponse
        /// </summary>
        [Fact]
        public void ScheduledMessageResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ScheduledMessageResponse
            //Assert.IsType<ScheduledMessageResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Messageid'
        /// </summary>
        [Fact]
        public void MessageidTest()
        {
            // TODO unit test for the property 'Messageid'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
