/*
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.
 *
 * The version of the OpenAPI document: 1.9.0
 * Contact: support@thesmsworks.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ScheduledMessagesResponseMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScheduledMessagesResponseMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ScheduledMessagesResponseMessage
        //private ScheduledMessagesResponseMessage instance;

        public ScheduledMessagesResponseMessageTests()
        {
            // TODO uncomment below to create an instance of ScheduledMessagesResponseMessage
            //instance = new ScheduledMessagesResponseMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ScheduledMessagesResponseMessage
        /// </summary>
        [Fact]
        public void ScheduledMessagesResponseMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" ScheduledMessagesResponseMessage
            //Assert.IsType<ScheduledMessagesResponseMessage>(instance);
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }
    }
}
