/*
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.
 *
 * The version of the OpenAPI document: 1.9.0
 * Contact: support@thesmsworks.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ScheduledMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScheduledMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ScheduledMessage
        //private ScheduledMessage instance;

        public ScheduledMessageTests()
        {
            // TODO uncomment below to create an instance of ScheduledMessage
            //instance = new ScheduledMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ScheduledMessage
        /// </summary>
        [Fact]
        public void ScheduledMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" ScheduledMessage
            //Assert.IsType<ScheduledMessage>(instance);
        }

        /// <summary>
        /// Test the property 'Sender'
        /// </summary>
        [Fact]
        public void SenderTest()
        {
            // TODO unit test for the property 'Sender'
        }

        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

        /// <summary>
        /// Test the property 'Destination'
        /// </summary>
        [Fact]
        public void DestinationTest()
        {
            // TODO unit test for the property 'Destination'
        }

        /// <summary>
        /// Test the property 'Destinations'
        /// </summary>
        [Fact]
        public void DestinationsTest()
        {
            // TODO unit test for the property 'Destinations'
        }

        /// <summary>
        /// Test the property 'Schedule'
        /// </summary>
        [Fact]
        public void ScheduleTest()
        {
            // TODO unit test for the property 'Schedule'
        }
    }
}
