/*
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.
 *
 * The version of the OpenAPI document: 1.9.0
 * Contact: support@thesmsworks.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ScheduledMessagesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScheduledMessagesResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ScheduledMessagesResponse
        //private ScheduledMessagesResponse instance;

        public ScheduledMessagesResponseTests()
        {
            // TODO uncomment below to create an instance of ScheduledMessagesResponse
            //instance = new ScheduledMessagesResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ScheduledMessagesResponse
        /// </summary>
        [Fact]
        public void ScheduledMessagesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ScheduledMessagesResponse
            //Assert.IsType<ScheduledMessagesResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Batch'
        /// </summary>
        [Fact]
        public void BatchTest()
        {
            // TODO unit test for the property 'Batch'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
