/*
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.
 *
 * The version of the OpenAPI document: 1.9.0
 * Contact: support@thesmsworks.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SendMessageResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SendMessageResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SendMessageResponse
        //private SendMessageResponse instance;

        public SendMessageResponseTests()
        {
            // TODO uncomment below to create an instance of SendMessageResponse
            //instance = new SendMessageResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SendMessageResponse
        /// </summary>
        [Fact]
        public void SendMessageResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SendMessageResponse
            //Assert.IsType<SendMessageResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Messageid'
        /// </summary>
        [Fact]
        public void MessageidTest()
        {
            // TODO unit test for the property 'Messageid'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Credits'
        /// </summary>
        [Fact]
        public void CreditsTest()
        {
            // TODO unit test for the property 'Credits'
        }

        /// <summary>
        /// Test the property 'CreditsUsed'
        /// </summary>
        [Fact]
        public void CreditsUsedTest()
        {
            // TODO unit test for the property 'CreditsUsed'
        }
    }
}
